import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/navbar';

import ToasterProvider from '@/providers/toaster-provider';

import { auth } from '@/auth';

import AuthModal from '@/components/modals/auth-modal';

import SearchModal from '@/components/modals/search-modal';
import DepositWdModal from '@/components/modals/deposit-wd-modal';

// import ClientOnly from '@/lib/client-only';
import { cn } from '@/lib/utils';
import PostModal from '@/components/modals/post-modal';
import DeleteModal from '@/components/modals/delete-modal';

import Footer from '@/components/footer';

import LiveScoreModal from '@/components/modals/live-score-modal';

import TopicModal from '@/components/modals/topic-modal';
import { SessionProvider } from 'next-auth/react';
import NoUserModal from '@/components/modals/no-user-modal';
import SoccerModal from '@/components/modals/soccer-modal';
import getCurrentUser from '@/actions/get-user';
import UserProfileModal from '@/components/modals/user-profile-modal';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
  className?: string;
};

export default async function RootLayout({
  children,
  className,
}: Readonly<RootLayoutProps>) {
  const currentUser = await getCurrentUser();

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <body
          className={cn(
            'flex flex-col justify-between overflow-x-hidden relative',
            inter.className,
            className
          )}
        >
          <ToasterProvider />
          <UserProfileModal />
          <SoccerModal />
          <TopicModal />
          <LiveScoreModal />
          <DeleteModal />
          <DepositWdModal />
          <PostModal />
          <SearchModal />
          <NoUserModal />
          <AuthModal />
          <Navbar currentUser={currentUser} />
          <div className='pb-4'>{children}</div>
          <div className='relative pb-20'>
            <Footer />
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
