name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.14.0]
    env:
      NEXT_PUBLIC_DOMAIN: ${{secrets.NEXT_PUBLIC_DOMAIN}}
      NEXT_PUBLIC_API_DOMAIN: ${{secrets.NEXT_PUBLIC_API_DOMAIN}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      AUTH_SECRET: ${{secrets.AUTH_SECRET}}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
      AUTH_TRUST_HOST: ${{secrets.AUTH_TRUST_HOST}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      GOOGLE_ID: ${{secrets.GOOGLE_ID}}
      GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
      GITHUB_ID: ${{secrets.GITHUB_ID}}
      GITHUB_SECRET: ${{secrets.GITHUB_SECRET}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
      AUTH_FACEBOOK_ID: ${{secrets.AUTH_FACEBOOK_ID}}
      AUTH_FACEBOOK_SECRET: ${{secrets.AUTH_FACEBOOK_SECRET}}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
