name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.14.0]
    env:
      NEXT_PUBLIC_DOMAIN: http://localhost:3000
      NEXT_PUBLIC_API_DOMAIN: http://localhost:3000/api
      DATABASE_URL: mongodb+srv://tom:2p1ik2swjSCvOulF@bookit.xknf1.mongodb.net/al?retryWrites=true&w=majority
      AUTH_SECRET: UJHo7DqvtDCLVCiPHl5fsAryaWPmm684yEH3DpVzoj8=
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: tommy08
      AUTH_TRUST_HOST: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      GOOGLE_ID: ${{secrets.GOOGLE_ID}}
      GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
      GITHUB_ID: ${{secrets.GITHUB_ID}}
      GITHUB_SECRET: ${{secrets.GITHUB_SECRET}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_CLOUD_NAME: tommy08
      AUTH_FACEBOOK_ID: ${{secrets.AUTH_FACEBOOK_ID}}
      AUTH_FACEBOOK_SECRET: ${{secrets.AUTH_FACEBOOK_SECRET}}

    steps:
      - name: Read a next public domain
        run: echo "My NEXT_PUBLIC_DOMAIN value is ${{env.NEXT_PUBLIC_DOMAIN}}"
      - name: Read a next Auth Secret
        run: echo "My NEXT_PUBLIC_DOMAIN value is ${{env.AUTH_SECRET}}"
      - name: Read a Database Url
        run: echo "My NEXT_PUBLIC_DOMAIN value is ${{env.DATABASE_URL}}"
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Change Directory
        run: cd /home/tom/actions-runner/_work/agliga/agliga
      - run: pm2 restart 1
